### ISSUE TITLE
Bridge not joining invitation

### ISSUE THREAD

**Issue by Boostflow** [JojiiOfficial/Matrix-EmailBridge#34]
I'm trying to configure this bridge and have a successful setup. I configured cfg.json and the log output confirms: `logged into matrix successfully`

When I invite the newly created bridge into a private room it's not joining. The user stays on "invited", no more details available in the log. Any advice where to start troubleshooting?

**Comment by JojiiOfficial** [comment]
What does the bridge say, any logs shown?

One Idea how you could start troubleshooting:
Downgrade 'maunium.net/go/mautrix' from `v0.1.0-beta.2` to an earlier version in the main/go.mod file. You can find earlier versions here:
https://github.com/tulir/mautrix-go/tags?after=v0.2.0-beta.2

I just picked the newest version which did compile. Since he rewrote a lot of his lib, the bridge fails to compile after a certain version. I don't use matrix myself anymore so I couldn't test it. If you manage to get it to work with an earlier version, I'll update the go.mod file.

**Comment by JojiiOfficial** [comment]
Closing due merge of #38 and inactivity.
